# -*- coding: utf-8 -*-
"""chemunitcal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xuvIYds_aZWJOoeLN90g0kxPudwSASpH
"""

AVOGADRO_NUMBER = 6.022e23
STP_VOLUME = 22.4

def grams_to_moles(mass, molar_mass):
    return mass / molar_mass

def moles_to_grams(moles, molar_mass):
    return moles * molar_mass

def particles_to_moles(particles):
    return particles / AVOGADRO_NUMBER

def moles_to_particles(moles):
    return moles * AVOGADRO_NUMBER

def volume_stp_to_moles(volume):
    return volume / STP_VOLUME

def moles_to_volume_stp(moles):
    return moles * STP_VOLUME

def main():
    while True:
        print("\nเลือกการแปลงหน่วย:")
        print("1. แปลงกรัมเป็นโมล")
        print("2. แปลงโมลเป็นกรัม")
        print("3. แปลงอนุภาคเป็นโมล")
        print("4. แปลงโมลเป็นอนุภาค")
        print("5. แปลงปริมาตร STP เป็นโมล")
        print("6. แปลงโมลเป็นปริมาตร STP")
        print("7. ออกจากโปรแกรม")

        choice = input("เลือกตัวเลือก (1-7): ")

        if choice == '1':
            mass = float(input("ป้อนมวล (กรัม): "))
            molar_mass = float(input("ป้อนมวลโมลาร์ (g/mol): "))
            print(f"ผลลัพธ์: {grams_to_moles(mass, molar_mass):.4f} โมล")
        elif choice == '2':
            moles = float(input("ป้อนจำนวนโมล: "))
            molar_mass = float(input("ป้อนมวลโมลาร์ (g/mol): "))
            print(f"ผลลัพธ์: {moles_to_grams(moles, molar_mass):.4f} กรัม")
        elif choice == '3':
            particles = float(input("ป้อนจำนวนอนุภาค: "))
            print(f"ผลลัพธ์: {particles_to_moles(particles):.4e} โมล")
        elif choice == '4':
            moles = float(input("ป้อนจำนวนโมล: "))
            print(f"ผลลัพธ์: {moles_to_particles(moles):.4e} อนุภาค")
        elif choice == '5':
            volume = float(input("ป้อนปริมาตรที่ STP (ลิตร): "))
            print(f"ผลลัพธ์: {volume_stp_to_moles(volume):.4f} โมล")
        elif choice == '6':
            moles = float(input("ป้อนจำนวนโมล: "))
            print(f"ผลลัพธ์: {moles_to_volume_stp(moles):.4f} ลิตรที่ STP")
        elif choice == '7':
            print("ออกจากโปรแกรม")
            break
        else:
            print("กรุณาเลือกตัวเลือกที่ถูกต้อง!")

if __name__ == "__main__":
    main()